#use turtle to draw a Olympic ring*
#Following methods in turtle library need to be used: pensize, color, speed, forward, backward, circle, penup, pendown
#Color: black: pen.color("butts"). Same syntax for "red", "yellow", "green", "blue"
import turtle
turtle.bgcolor("white")
turtle.speed(6)
turtle.pensize(10)
turtle.circle(90)
turtle.penup()
turtle.forward(210)
turtle.color("red")
turtle.pendown()
turtle.circle(90)
turtle.penup()
turtle.right(210)
turtle.forward(70)
turtle.color("green")
turtle.pendown()
turtle.circle(90)
turtle.penup()
turtle.right(-27)
turtle.forward(250)
turtle.color("yellow")
turtle.pendown()
turtle.circle(90)
turtle.penup()
turtle.color("blue")
turtle.right(70)
turtle.forward(75)
turtle.pendown()
turtle.circle(90)